name: Python Deployment Workflow


run-name: ${{ github.actor }} - ${{ github.sha }}


env:
  PythonVersion: 3.8


on: 
  push: 
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]


jobs:
  python-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .src


    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PythonVersion }}
    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install flake8


    - name: Run tests    
      run: |
        python manage.py test

    - name: Generate coverage report
      run: coverage run manage.py test

    - name: Display coverage report
      run: coverage report

    - name: Check code style
      run: flake8 . --show-source --statistics